### ISSUE TITLE
[Suggestion] Provide documentation for env vars and endpoints

### ISSUE THREAD

**Issue by F9Alejandro** [Inrixia/LostMokoko#2]
Just a quick suggestion to provide information about the endpoints to be sure that discord is pushed to the correct usage case.

e.g. /interaction for the interaction gateway
/setup for command initial setup
/ for bot join

another thing to keep in mind is the naming scheme for the variables, CLIENT_SECRET doesn't make much sense when it is actually the bot token being used. CLIENT_ID and PUBLIC_KEY makes perfect sense and is to the point of what they should be.

**Comment by Inrixia** [comment]
I believe this issue is meant to be on my fork of `cloudflare-discord-bot` (https://github.com/Inrixia/cloudflare-discord-bot)

As for those, yes the repo lacks proper documentation for many things and has various issues. If @alvgaona is not responsive in working on merging changes etc then I may just migrate my fork to its own repo and npm package.

Regardless if you have any suggestions feel free to open them on my repo.

**Comment by F9Alejandro** [comment]
Thank you for the timely response was not expecting that tbh. Just need the issues to be enabled for your fork of cloudflare-discord-bot then I can provide requests and responses to help the project out (really like the idea and will try putting it to use)

+1 for being an alternative for using autocode and their limited requests per month (100,000 per day still seems crazy, then again it is cloudflare, they are massive)

**Comment by Inrixia** [comment]
Done

**Comment by alvgaona** [comment]
Hi, @Inrixia @F9Alejandro sorry for my unresponsiveness. It's been quite a hectic month, personally.

Would you guys like to create an organization where we could all have a say in how we want this framework to evolve? We'd be unblocking dependencies on a single person, in terms of merges, and whatnot.

I created [this org](https://github.com/cf-discord) a few months ago, would you like to be added there? Then, we could migrate my repo to it.

**Comment by F9Alejandro** [comment]
I would be down for that. Would also like to see the possibility of getting a bot that handles the events like when a user joins the server or getting events when a user joins and/or leaves a voice channel.

**Comment by Inrixia** [comment]
@F9Alejandro I presume what your talking about is translating discords real-time gateway events to web hooks. Something which is sadly outside the scope of this project currently.

That said having a generic runnable which when given a token and endpoint could enable gateway functionality would be cool

**Comment by F9Alejandro** [comment]
^ Would just need something small with barely any processing power to get done since most of the interactions would be through cloudflare workers and websocket gateway would be nice. Generic little runnable.

**Comment by alvgaona** [comment]
@F9Alejandro feel free to join here so we can discuss all your concerns and requests: https://discord.gg/TsgkrwMR
